services:
  notifications-service:
    build: ./
    container_name: notifications-service
    ports:
      - "4089:4089"
    expose:
      - "4089"
    networks:
      - fcNet
      - jaegerNet
      - notificationsNet
    env_file:
      - ./.env
    environment:
      TZ: ${TIMEZONE}
      SPRING_PROFILES_ACTIVE: "docker"
      OTEL_RESOURCE_ATTRIBUTES: ${OTEL_RESOURCE_ATTRIBUTES}
      OTEL_EXPORTER_OTLP_PROTOCOL: ${OTEL_EXPORTER_OTLP_PROTOCOL}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      OTEL_METRIC_EXPORT_INTERVAL: ${OTEL_METRIC_EXPORT_INTERVAL}


networks:
  fcNet:
    name: fcNet
    external: true
  notificationsNet:
    name: notificationsNet
    external: true
  jaegerNet:
    name: jaegerNet
    external: true
