services:
  notifications-service:
    image: ${ECR_REPOSITORY}/fc-notifications-service:latest
    container_name: notifications-service
    ports:
      - "4089:4089"
    expose:
      - "4089"
    networks:
      - fcNet
      - jaegerNet
      - notificationsNet
    env_file:
      - ./.env
    environment:
      TZ: ${TIMEZONE}
      OTEL_SERVICE_NAME: "notifications-service"
      SPRING_PROFILES_ACTIVE: "docker"
      OTEL_RESOURCE_ATTRIBUTES: ${OTEL_RESOURCE_ATTRIBUTES}
      OTEL_EXPORTER_OTLP_PROTOCOL: ${OTEL_EXPORTER_OTLP_PROTOCOL}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      OTEL_METRIC_EXPORT_INTERVAL: ${OTEL_METRIC_EXPORT_INTERVAL}

  postgresdb:
    container_name: postgresdb
    image: postgres:latest
    restart: always
    depends_on:
      - api-gateway
    networks:
      - fcNet
      - jaegerNet
      - notificationsNet
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"


networks:
  fcNet:
    name: fcNet
    external: true
    driver: bridge
  notificationsNet:
    name: notificationsNet
    external: true
    driver: bridge
  jaegerNet:
    name: jaegerNet
    external: true
    driver: bridge